name: Make PR

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Make a change
      id: change
      run: |
        git checkout -b changes || git checkout changes
        git reset --hard origin/master
        echo 456 > test.txt
        git config --local user.email "techops@laws.africa"
        git config --local user.name Laws.Africa

        git diff --exit-code && exit 0
        
        git add test.txt
        git commit -m "changed test.txt"
        git push -u origin changes --force
        echo "::set-output name=summary::hello"

    # Runs a set of commands using the runners shell
    - name: Create PR
      uses: actions/github-script@0.9.0
      if: steps.change.outputs.summary
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          const info = {
            owner: "laws-africa",
            repo: "action-tester",
            title: "Updated a file",
            body: '👋 I made a change!',
            base: 'master',
          };
          const resp = await github.pulls.list({
            owner: context.repo.owner,
            repo: context.repo.repo,
            state: "open",
            head: "changes",
            base: "master",
          });
          if (resp.data.length > 0) {
            github.pulls.update({...info, pull_number: resp.data[0].number});
          } else {
            github.pulls.create({...info, head: 'changes'});
          }
